### ISSUE TITLE
Import data to database : doesn't work

### ISSUE THREAD

**Issue by sachinsshetty** [GoogleChromeLabs/sample-pie-shop#127]
Below steps are failing 

cd tools
node import_home.js
node import_products.js

node import_home.js 
/home/pi/github/work/chocolate_web/sample-pie-shop/tools/import_home.js:15
import initializeApp from '../services/firebase';
       ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)

**Comment by sachinsshetty** [comment]
solved the error by  replacing
import initializeApp from '../services/firebase';
with
const admin = require('firebase-admin');
admin.initializeApp();
